extends SceneTree
# C18 acceptance probe (docs/specs/whirlpools.md §Verify) — the whirlpool contract: (1) two-world
# determinism under the pull, (2) the disabled/ungenerated baseline is byte-identical and
# generate() makes ZERO world.rng draws, (3) same seed ⇒ same charted site, start clearing held,
# (4) the tide clock is bounded + deterministic, (5) mass tiers observable (small craft drift,
# subs immune, torpedoes bend, the battleship feels a nudge), (6) the grinder law (kills at peak
# core only, full XP; subs immune; NEVER hull damage), (7) the helm fight torques the bow only in
# the core at high tide.

const DT: float = 1.0 / 60.0

func _initialize() -> void:
	var fails: int = 0
	var peak: int = Configs.defaults().whirlpool.tide_period / 2

	# 1 — determinism: vortex at peak tide, orbiting gunboats + a torpedo under the pull
	var c1 := _quiet()
	var wa := _vortex_world(15, c1, peak)
	var wb := _vortex_world(15, c1, peak)
	for i in range(3600):
		for w in [wa, wb]:
			w.input.thrust = 1.0 if i % 600 < 300 else 0.0
			w.input.rudder = 1.0 if i % 500 < 250 else -1.0
			Sim.step(w, DT, c1)
			w.effects.clear()
	var same: bool = wa.ship_pos == wb.ship_pos and wa.ship_heading == wb.ship_heading \
		and wa.hull == wb.hull and wa.rng.calls == wb.rng.calls and wa.kills == wb.kills
	for i in range(wa.enemies.size()):
		same = same and wa.enemies[i].pos == wb.enemies[i].pos
	fails += _check(same, "determinism: 3600 ticks under the pull byte-identical (rng.calls %d, kills %d)" % [wa.rng.calls, wa.kills])

	# 2 — baseline: generate() never touches world.rng; disabled == ungenerated through combat
	var c2 := _quiet()
	var c2off := _quiet()
	c2off.whirlpool.enabled = false
	var w2a := GameWorld.new(88)
	var w2b := GameWorld.new(88)
	Terrain.generate(w2a, c2)
	Terrain.generate(w2b, c2off)
	var calls0: int = w2b.rng.calls
	Whirlpool.generate(w2b, c2off)                      # disabled ⇒ charts nothing
	var w2c := GameWorld.new(88)
	Terrain.generate(w2c, c2)
	Whirlpool.generate(w2c, c2)                         # enabled ⇒ still zero world.rng draws
	var zero_draws: bool = w2b.rng.calls == calls0 and w2c.rng.calls == w2a.rng.calls \
		and w2b.vortex_pos.x == INF
	for i in range(1200):
		for w in [w2a, w2b]:
			w.input.thrust = 1.0
			Sim.step(w, DT, c2)
			w.effects.clear()
	fails += _check(zero_draws and w2a.ship_pos == w2b.ship_pos and w2a.rng.calls == w2b.rng.calls,
		"baseline: generate() drew 0 from world.rng; disabled == ungenerated byte-identical")

	# 3 — placement: same seed ⇒ same charted site; the opening water stays clear
	var c3 := _quiet()
	var w3a := GameWorld.new(777)
	var w3b := GameWorld.new(777)
	Terrain.generate(w3a, c3)
	Terrain.generate(w3b, c3)
	Whirlpool.generate(w3a, c3)
	Whirlpool.generate(w3b, c3)
	var placed: bool = w3a.vortex_pos.x != INF and w3a.vortex_pos == w3b.vortex_pos
	var clear_ok: bool = w3a.vortex_pos.distance_to(Vector2.ZERO) >= c3.whirlpool.start_clear
	fails += _check(placed and clear_ok,
		"placement: same seed ⇒ same site (%.0f,%.0f), %.0fu from the start (≥%.0f)" \
		% [w3a.vortex_pos.x, w3a.vortex_pos.y, w3a.vortex_pos.length(), c3.whirlpool.start_clear])

	# 4 — the tide clock: bounded [floor,1], deterministic, dormant at wave 0, full at period/2
	var c4 := _quiet()
	var w4 := GameWorld.new(5)
	var tide_ok: bool = true
	for wv in range(0, 3 * c4.whirlpool.tide_period):
		w4.wave = wv
		var t1: float = Whirlpool.tide(w4, c4)
		tide_ok = tide_ok and t1 == Whirlpool.tide(w4, c4) \
			and t1 >= c4.whirlpool.tide_floor - 0.001 and t1 <= 1.001
	w4.wave = 0
	var dormant: bool = absf(Whirlpool.tide(w4, c4) - c4.whirlpool.tide_floor) < 0.01
	w4.wave = peak
	var full: bool = Whirlpool.tide(w4, c4) > 0.99
	fails += _check(tide_ok and dormant and full,
		"tide clock: bounded + deterministic; floor at wave 0, full churn at wave %d" % peak)

	# 5 — mass tiers: the gunboat drifts, the sub doesn't, the torpedo bends, the hull feels a nudge
	var off := Vector2(100, 0)
	var gb_moved: float = _drift_of("gunboat", peak, true)
	var gb_still: float = _drift_of("gunboat", peak, false)
	var sub_moved: float = _drift_of("sub", peak, true)
	var cT := _quiet()
	var wt_on := _vortex_world(9, cT, peak)
	var wt_off := GameWorld.new(9)
	Sim.step(wt_off, DT, cT)
	wt_off.wave = peak            # no vortex charted — the control world; same spawn point for both
	var pa := _spawn_torp(wt_on, wt_on.vortex_pos)
	var pb := _spawn_torp(wt_off, wt_on.vortex_pos)
	for i in range(150):
		Sim.step(wt_on, DT, cT)
		Sim.step(wt_off, DT, cT)
		wt_on.effects.clear()
		wt_off.effects.clear()
	var torp_bent: bool = pa.pos.distance_to(pb.pos) > 8.0
	var cS := _quiet()
	var wS := _vortex_world(3, cS, peak)
	wS.ship_pos = wS.vortex_pos + Vector2(80, 0)
	var v0: float = wS.ship_vel.length()
	_run(wS, cS, 3.0)
	var nudged: bool = wS.ship_vel.length() - v0 > 0.5 and wS.hull == 10
	# dormant is the FLOOR, not zero — the lane never fully sleeps; assert the tide dominates
	fails += _check(gb_moved > 5.0 and gb_still < gb_moved * 0.25 and sub_moved < 0.001 and torp_bent and nudged,
		"mass tiers: gunboat drifted %.1fu (dormant %.1fu), sub %.3fu, torpedo bent %.1fu, hull nudged and undamaged" \
		% [gb_moved, gb_still, sub_moved, pa.pos.distance_to(pb.pos)])

	# 6 — the grinder: a small craft in the core at peak capsizes at full XP; below the threshold
	#     and subs survive; the battleship parked in the eye takes ZERO hull damage
	var c6 := _quiet()
	c6.enemies.by_id("gunboat").speed = 0.0
	c6.enemies.by_id("gunboat").fire_range = 0.0
	c6.enemies.by_id("sub").speed = 0.0
	c6.enemies.by_id("sub").fire_range = 0.0
	var w6 := _vortex_world(21, c6, peak)
	_place(w6, "gunboat", w6.vortex_pos + Vector2(5, 0), 999999, c6)   # only the grinder may end it
	var caps: int = _count_fx(w6, c6, 1.5, "capsize")
	var ground: bool = not w6.enemies[0].active and w6.kills == 1 \
		and w6.xp_run == c6.progress.xp_for_kill("gunboat") and caps >= 1
	var w6b := _vortex_world(22, c6, 0)   # dormant tide
	_place(w6b, "gunboat", w6b.vortex_pos + Vector2(5, 0), 999999, c6)
	_run(w6b, c6, 2.0)
	var survived_low: bool = w6b.enemies[0].active
	var w6c := _vortex_world(23, c6, peak)
	_place(w6c, "sub", w6c.vortex_pos + Vector2(5, 0), 999999, c6)
	_run(w6c, c6, 2.0)
	var sub_safe: bool = w6c.enemies[0].active
	var w6d := _vortex_world(24, c6, peak)
	w6d.ship_pos = w6d.vortex_pos
	_run(w6d, c6, 8.0)
	var hull_safe: bool = w6d.hull == 10
	fails += _check(ground and survived_low and sub_safe and hull_safe,
		"grinder: peak-core capsize %s (kills %d, xp %d/%d, fx %d); dormant survives %s; sub immune %s; hull safe %s (%d)" \
		% [ground, w6.kills, w6.xp_run, c6.progress.xp_for_kill("gunboat"), caps, survived_low, sub_safe, hull_safe, w6d.hull])

	# 7 — the helm fight: rudder amidships, the core at high tide torques the bow; open water doesn't
	var c7 := _quiet()
	var w7a := _vortex_world(31, c7, peak)
	w7a.ship_pos = w7a.vortex_pos + Vector2(3, 0)
	var h0: float = w7a.ship_heading
	_run(w7a, c7, 1.0)
	var w7b := GameWorld.new(31)
	Sim.step(w7b, DT, c7)
	var h0b: float = w7b.ship_heading
	_run(w7b, c7, 1.0)
	fails += _check(absf(w7a.ship_heading - h0) > 0.02 and w7b.ship_heading == h0b,
		"helm fight: bow torqued %.3f rad in the eye at peak; open water untouched" % absf(w7a.ship_heading - h0))

	print("\nprobe_whirlpool: %s" % ("ALL GREEN" if fails == 0 else "%d FAILED" % fails))
	quit(fails)

# A quiet world with the vortex charted by hand at a known spot and the tide forced by wave count
# (white-box: tide is a pure function of world.wave; the director is frozen so it never advances).
func _vortex_world(seed_val: int, c: Configs, wave: int) -> GameWorld:
	var w := GameWorld.new(seed_val)
	Sim.step(w, DT, c)
	w.vortex_pos = Vector2(260, -260)
	w.wave = wave
	return w

func _drift_of(type_id: String, wave: int, vortex_on: bool) -> float:
	var c := _quiet()
	c.enemies.by_id(type_id).speed = 0.0
	c.enemies.by_id(type_id).fire_range = 0.0
	var w := _vortex_world(7, c, wave)
	if not vortex_on:
		w.wave = 0   # dormant tide stands in for "no vortex": floor-level drift only
	var start: Vector2 = w.vortex_pos + Vector2(100, 0)
	_place(w, type_id, start, 999999, c)   # unkillable — the ship's own turrets must not end the measurement
	_run(w, c, 2.0)
	return w.enemies[0].pos.distance_to(start)

func _spawn_torp(w: GameWorld, origin: Vector2) -> Projectile:
	var p: Projectile = w.projectiles.obtain()
	p.pos = origin + Vector2(-300, 60)   # a run through the meat of the field, 60u off the eye
	p.vel = Vector2(130, 0)
	p.dmg = 0
	p.splash = 0.0
	p.hostile = true
	p.wid = "torpedo"
	p.life = 8.0
	return p

func _quiet() -> Configs:
	var c := Configs.defaults()
	c.waves.base_budget = 0
	c.waves.budget_per_wave = 0
	c.waves.first_wave_delay = 1e12
	return c

func _place(w: GameWorld, type_id: String, pos: Vector2, hp_override: int, c: Configs) -> void:
	var def: EnemyDef = c.enemies.by_id(type_id)
	var e := Enemy.new()
	e.type_id = def.id
	e.layer = def.layer
	e.active = true
	e.pos = pos
	e.heading = atan2(w.ship_pos.x - pos.x, -(w.ship_pos.y - pos.y))
	e.hp_max = def.hp
	e.hp = hp_override if hp_override > 0 else def.hp
	w.enemies.append(e)

func _run(w: GameWorld, c: Configs, secs: float) -> void:
	for i in range(int(round(secs / DT))):
		Sim.step(w, DT, c)
		w.effects.clear()

func _count_fx(w: GameWorld, c: Configs, secs: float, fx_type: String) -> int:
	var n: int = 0
	for i in range(int(round(secs / DT))):
		Sim.step(w, DT, c)
		for e in w.effects:
			if e["type"] == fx_type:
				n += 1
		w.effects.clear()
	return n

func _check(cond: bool, label: String) -> int:
	print(("  OK  " if cond else "  FAIL") + " — " + label)
	return 0 if cond else 1
